### ISSUE TITLE
Screen calibration tool has strange behavior

### ISSUE THREAD

**Issue by micbuffa** [arcadeforge/regamebox#14]
Hi! I used the screen calibration tool on my scart RGB CRT TV. I used arrows and key 1 to go through the different steps. At the end, a dialog appears with -I suppose- an ok and a cancel button. This dialog is so stretched vertically that I cannot read the button labels. So, I blindly tried the button on the left and could not see any effect on my screen. I also redone the whole process and validated with the right button on the stretched dialog -> same result.

My suggestion: first fix the stretched dialog problem. Then check that the wizard saves correctly. For me it seems to have not effect after calibration.

I used 2.7 straight from download, then applied online patch 2.7.5

**Comment by arcadeforge** [comment]
Profiles are not needed anymore.
