### ISSUE TITLE
Regamebox 2.7.5 : setting menu resolution : calibration screen does not react to keys

### ISSUE THREAD

**Issue by micbuffa** [arcadeforge/regamebox#19]
I tried the "menu screen resolution option" and a calibration screen appeared, but no key reacted, arrows, etc. or if they reacted it was very confusing. Numbers on the hdmi setting line on top changed a little then nothing... I managed to quit pressing Q. As I could not change anything I could not see a difference.

**Comment by arcadeforge** [comment]
Reworked in 2.9

https://mega.nz/#!NJQjlIqS!UfWTfHj0BT7dPRsQA_khQA_Nsb8M98Jo6Vox-RRRRG8

**Comment by arcadeforge** [comment]
Complete new reworked timing config menu in 3.1
