### ISSUE TITLE
Set Menu Overscan broke the current res + I can't reboot anymore

### ISSUE THREAD

**Issue by micbuffa** [arcadeforge/regamebox#21]
Hi, I used the set menu overscan option and it had a very strange behavior: first it displayed a set of random dots, as told in the previous dialog. I used arrows to move a few pixels right and down the screen. Then pressed Q. A dialog reappeared. I had to press Q again to save and exit.

Then the main screen with option menus etc was stretched horizontally and took only the center of the screen width with large black bars on left and right.

I went again to the menu overscan calibration screen but this time the random dots were displayed with black bars on top/left/right/bottom, I left as is and saved again.

Main menu was still centered and stretched. I rebooted using the system menu.

The image boots, nothing on screen (black), red led lit and green kept flashing for 30 minutes... nothing happens...

**Comment by micbuffa** [comment]
Hmmm apparently, using the set menu overscan removed the config.txt file. Ouch.

**Comment by arcadeforge** [comment]
Reworked in 2.9

https://mega.nz/#!NJQjlIqS!UfWTfHj0BT7dPRsQA_khQA_Nsb8M98Jo6Vox-RRRRG8
