### ISSUE TITLE
Messed up configs from brand new 3.1.8 setup

### ISSUE THREAD

**Issue by Spider-webber** [arcadeforge/regamebox#39]
Just arrived a brand new PI2Jamma\PI3-B+ with Regame 3.1.8,

After first startup I've noticed that game were correctly displayed on my screen but with lots of overscan, so I've tried to change configs, but totally screwed all.

Now I'm in need to go back to "factory settings" but unfortunately I've lost image I've made.
On the main website there a 10gb image that is considered the "standard image" but it's only the 3.1.4, mine's 3.1.8.

Please guide me to rescue my first installation.

**Comment by arcadeforge** [comment]
Glad you sorted it
