### ISSUE TITLE
retroarch not logging

### ISSUE THREAD

**Issue by milnak** [arcadeforge/regamebox#60]
even with DEBUG  (verbose), im not seeing anything in /mnt/sda/retroarch.log

I even tried changing autostart.sh to:

`retroarch --log-file /mnt/sda/retroarch.log ...`

without any output.  Does retroarch not log?

**Comment by arcadeforge** [comment]
Added to launch selection

**Comment by AndyHazz** [comment]
I noticed retroarch.log is saved at /retroarch.log on v3.2.2 which doesn't seem right?
It looks like there might be a typo in autostart.sh ...

line 382 has $USB_PATCH that I think should be $USB_PATH?

```
    if [ -e "$USB_PATH" ]; then
        cp /root/launch.log $USB_PATCH/retroarch.log
    fi
```

... I'm no coder so apologies if this is irrelevant, I just spotted it whilst looking for something else :)

**Comment by arcadeforge** [comment]
$USB_PATCH should be USB_PATH
