### ISSUE TITLE
V3. 2 add pushb theme

### ISSUE THREAD

**Issue by arcadeforge** [arcadeforge/regamebox#63]
Here's the vertical theme files if anyone would like to try: https://drive.google.com/file/d/1ZMwAO3JtJIj_xlK0-UXjtkVhGf4tfoP6/view?usp=sharing

Horizontal theme I shared earlier: https://drive.google.com/file/d/12HwxpldFzBtovLzpLJuOXKyChzhsWupb/view?usp=sharing

I figured out how to get them into the theme menu properly but it's a bit fiddly ... after extracting the zips into folders in '/root/themes/themes/', you then need to add them to '/root/databases/themes.list', '/root/no_scale_themes.list' (not sure why but if you don't do that then the mame logos won't display correctly), and '/root/frontend/themes.conf'

**Comment by AndyHazz** [comment]
I started putting the files into a branch ready to PR for you, but realised this repo isn't yet updated with your 3.2 release, so the way the themes work is different ... I'll leave it up to you :)

**Comment by AndyHazz** [comment]
I've been testing my theme with your latest release, I think I need to adjust the positioning a bit to centre on screen better.

I had messed around with the HDMI timings in the past which meant my setup wasn't quite standard, now with your new 3.2 image the default HDMI timings seem fine for me, so I will optimise the theme for that. Basically I think I need to shift everything 9 pixels to the left.

**Comment by arcadeforge** [comment]
perfect. Themes go here

https://github.com/arcadeforge/regamebox_themes

So we can add themes when ever we want. Feel free to make a pr or write issues for other themes.

**Comment by arcadeforge** [comment]
In 3.2.2
